apiVersion: v1
kind: ConfigMap
metadata:
  name: tectonic-monitoring
  namespace: openshift-monitoring
data:
  config.yaml: |+
    prometheusOperator:
      baseImage: quay.io/coreos/prometheus-operator-dev
      prometheusConfigReloaderBaseImage: quay.io/coreos/prometheus-config-reloader
      configReloaderBaseImage: quay.io/coreos/configmap-reload
    prometheusK8s:
      baseImage: quay.io/prometheus/prometheus
    alertmanagerMain:
      baseImage: quay.io/prometheus/alertmanager
    ingress:
      baseAddress: prometheus.openshift-monitoring.svc
