---
- name: Create temp directory for doing work in on target
  command: mktemp -td openshift-cluster-monitoring-ansible-XXXXXX
  register: mktemp
  changed_when: False

- name: Copy files to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ mktemp.stdout }}/{{ item }}"
  with_items:
  - cluster-monitoring-operator.yaml

- name: Copy admin client config
  command: >
    cp {{ openshift.common.config_base }}/master/admin.kubeconfig {{ mktemp.stdout }}/admin.kubeconfig
  changed_when: false

- name: Add monitoring project
  oc_project:
    state: present
    name: openshift-monitoring
    description: Openshift Monitoring
    node_selector: ""

#TODO Remove need for cluster-admin permission
- name: Add cluster admin permission
  command: >
    {{ openshift_client_binary }} adm policy add-cluster-role-to-user cluster-admin -z default
    --config={{ mktemp.stdout }}/admin.kubeconfig
    -n openshift-monitoring

- name: Apply the cluster monitoring operator template
  shell: >
    {{ openshift_client_binary }} process -f "{{ mktemp.stdout 	}}/{{ item }}"
    --param OPERATOR_IMAGE="{{ openshift_cluster_monitoring_operator_image }}"
    --param PROMETHEUS_OPERATOR_IMAGE="{{ openshift_cluster_monitoring_operator_prometheus_operator_image }}"
    --param ALERTMANAGER_IMAGE="{{ openshift_cluster_monitoring_operator_alertmanager_image }}"
    --param PROMETHEUS_IMAGE="{{ openshift_cluster_monitoring_operator_prometheus_image }}"
    --param PROMETHEUS_CONFIG_RELOADER_IMAGE="{{ openshift_cluster_monitoring_operator_prometheus_reloader_image }}"
    --param CONFIG_RELOADER_IMAGE="{{ openshift_cluster_monitoring_oeprator_configmap_reloader_image }}"
    --config={{ mktemp.stdout }}/admin.kubeconfig
    | {{ openshift_client_binary }} apply --config={{ mktemp.stdout }}/admin.kubeconfig -f -
  with_items:
  - cluster-monitoring-operator.yaml

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
