---
- name: Create temp directory for doing work in on target
  command: mktemp -d openshift-cluster-monitoring-ansible-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"
    # TODO: remove
    openshift_client_binary: /usr/bin/oc
    openshift:
      common:
        config_base: /etc/origin

- name: Copy files to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ mktemp.stdout }}/{{ item }}"
  with_items:
  - app-version.yaml
  - app-version-openshift-monitoring.yaml
  - cluster-monitoring-operator.yaml
  - monitoring-config.yaml
  - project.yaml

- name: Copy admin client config
  command: >
    cp {{ openshift.common.config_base }}/master/admin.kubeconfig {{ mktemp.stdout }}/admin.kubeconfig
  changed_when: false

- name: Ensure monitoring project exists
  command: >
    {{ openshift_client_binary }} apply -f "{{ mktemp.stdout }}/project.yaml"
    --config={{ mktemp.stdout }}/admin.kubeconfig

- name: Use monitoring project
  command: >
    {{ openshift_client_binary }} project openshift-monitoring
    --config={{ mktemp.stdout }}/admin.kubeconfig

# FIXME maybe we need to change the manifests so this is not needed,
# or at least change it from default to something more specific
- name: Add cluster admin permission
  command: >
    {{ openshift_client_binary }} adm policy add-cluster-role-to-user cluster-admin -z default
    --config={{ mktemp.stdout }}/admin.kubeconfig
    -n openshift-monitoring

- name: Apply the cluster monitoring operator manifests
  command: >
    {{ openshift_client_binary }} apply -f "{{ mktemp.stdout }}/{{ item }}"
    --config={{ mktemp.stdout }}/admin.kubeconfig
    -n openshift-monitoring
  with_items:
  - monitoring-config.yaml
  - app-version.yaml
  - app-version-openshift-monitoring.yaml
  - cluster-monitoring-operator.yaml

#TODO: Maybe Routes should be configured by the Operator, not by ansible?
- name: Wait for Operator to create the prometheus service
  command: "{{ openshift_client_binary }} get service prometheus"
  register: result
  until: result.rc == 0
  retries: 90
  delay: 2

- name: Expose prometheus-k8s service
  oc_route:
    name: prometheus-k8s
    service_name: prometheus-k8s
    namespace: openshift-monitoring
    state: present

- name: Wait for Operator to create the alertmanager-main service
  command: "{{ openshift_client_binary }} get service alertmanager-main"
  register: result
  until: result.rc == 0
  retries: 90
  delay: 2

- name: Expose alertmanager-main service
  oc_route:
    name: alertmanager-main
    service_name: alertmanager-main
    namespace: openshift-monitoring
    state: present

- name: Wait for Operator to create the grafana service
  command: "{{ openshift_client_binary }} get service grafana"
  register: result
  until: result.rc == 0
  retries: 90
  delay: 2

- name: Expose grafana service
  oc_route:
    name: grafana
    service_name: grafana
    namespace: openshift-monitoring
    state: present

- name: Delete temp directory
  file:
    name: "{{ tempdir }}"
    state: absent
  changed_when: False
